config/routes.rb
Rails.application.routes.draw do
    resources :users do
    collection { post :import }
  end

    resources :playlists do
    collection { post :import }

  end
  
    resources :mp3s do
    collection { post :import }
  end    

    root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mp3.rb
class Mp3 < ApplicationRecord
  belongs_to :user, optional: true
  require 'csv'
  def self.import(file)
	encoding_options = {
	  :invalid           => :replace, 
	  :undef             => :replace,  
	  :replace           => '',       
	  :universal_newline => true     
	}

  	CSV.foreach(file.path, headers: true, :header_converters => lambda { |h| h.downcase.gsub(' ', '_').encode(Encoding.find('ASCII'), encoding_options) } ) do |row|
  	  Mp3.create! row.to_hash rescue nil
  	end
  end
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user, optional: true
  require 'csv'
  def self.import(file)
  	CSV.foreach(file.path, headers:true) do |row|
  	  Playlist.create! row.to_hash
  	end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :playlists
  has_many :mp3s
  require 'csv'
  def self.import(file)
  	CSV.foreach(file.path, headers:true) do |row|
  	  User.create! row.to_hash
  	end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/mp3s_controller.rb
class Mp3sController < ApplicationController
  def index
  	@mp3s = Mp3.all
  end

  def import
  	Mp3.import(params[:file])
  	redirect_to mp3s_url, notice: "Song Data imported"
  end	
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  def index
  	@playlists = Playlist.all
  end

  def import
  	Playlist.import(params[:file])
  	redirect_to playlists_url, notice: "Playlist Data imported"
  end	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all

    respond_to do |format|
      format.html
      format.json { render json: @users }
    end
  end

  def import
  	User.import(params[:file])
  	redirect_to root_url, notice: "User Data imported"
  end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlaylistApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mp3s/index.html.erb
<%= flash[:notice] %>
<table>
  <thead>
  	<tr>
  	  <th>Title</th>
      <th>Artist</th>
      <th>Album</th>
  	  <th>Track</th>
  	  <th>Year</th>
      <th>Genre</th>
  	</tr>
  </thead>
  <tbody>
  	<% @mp3s.each do |mp3| %>
  	  <tr>
  	  	<td><%= mp3.title %></td>
  	  	<td><%= mp3.interpret %></td>
  	  	<td><%= mp3.album %></td>
        <td><%= mp3.track %></td>
        <td><%= mp3.year %></td>
        <td><%= mp3.genre %></td>
  	  </tr>
  	<% end %>
  </tbody>
</table>
<div>

<h4>Import data</h4>
  <%= form_tag import_mp3s_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import CSV" %>
  <% end %>
</div>

app/views/playlists/index.html.erb
<%= flash[:notice] %>
<table>
  <thead>
  	<tr>
  	  <th>User ID</th>
  	  <th>Name</th>
  	  <th>Songs</th>
  	</tr>
  </thead>
  <tbody>
  	<% @playlists.each do |playlist| %>
  	  <tr>
  	  	<td><%= playlist.user_id %></td>
  	  	<td><%= playlist.name %></td>
  	  	<td><%= playlist.mp3_ids.split(',').map { |id| Mp3.find(id) rescue nil }.compact.map &:title %></td>
  	  </tr>
  	<% end %>
  </tbody>
</table>
<div>

<h4>Import data</h4>
  <%= form_tag import_playlists_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import CSV" %>
  <% end %>
</div>

app/views/users/index.html.erb
<%= flash[:notice] %>
<table>
  <thead>
  	<tr>
  	  <th>First Name</th>
  	  <th>Last Name</th>
  	  <th>Email</th>
  	  <th>Username</th>
      <th>Playlists</th>
  	</tr>
  </thead>
  <tbody>
  	<% @users.each do |user| %>
  	  <tr>
  	  	<td><%= user.first_name %></td>
  	  	<td><%= user.last_name %></td>
  	  	<td><%= user.email %></td>
  	  	<td><%= user.user_name %></td>
        <td><%= user.playlists.map &:name %></td>
  	  </tr>
  	<% end %>
  </tbody>
</table>
<div>

<h4>Import data</h4>
  <%= form_tag import_users_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import CSV" %>
  <% end %>
</div>